import '@/styles/globals.css'
import Footer from '@/components/layouts/Footer'
import Header from '@/components/layouts/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className="">
        <div className="">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
